version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_AgentManifest_AZSPROProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_AgentManifest_AZSPROProject
  gitUsername: karthikbm
  gitBranch: main
